// 字段中英文映射
export const FIELD_NAME_MAP = {
  name: '姓名',
  mobile: '手机号',
  gender: '性别',
  email: '邮箱',
  work_year: '工作年限',
  home_location: '籍贯',
  self_evaluation: '自我评价',
  willing_location_list: '期望工作地点',
  willing_position_list: '期望职位',
  social_links: '社交链接',
  date_of_birth: '出生日期',
  current_location: '当前所在地',
  new_content: '识别内容',
  award_list: '获奖经历',
  education_list: '教育经历',
  career_list: '工作经历',
  language_list: '语言能力',
  certificate_list: '证书',
  competition_list: '竞赛经历',
  project_list: '项目经历',
  file_url: '简历文件',
} as const;

// 公司信息表字段中英文映射
export const COMPANY_FIELD_NAME_MAP = {
  short_name: '公司简称',
  is_boss_verified: '是否boss认证',
  logo: '公司 LOGO',
  industry: '行业',
  financing_stage: '融资阶段',
  company_size: '公司规模',
  introduction: '公司简介',
  photo_album: '公司相册',
  // talent_development: '人才发展',
  // product_introduction: '产品介绍',
  address: '公司地址',
  company_name: '企业名称',
  legal_representative: '法定代表人',
  establishment_date: '成立时间',
  company_type: '企业类型',
  business_status: '经营状态',
  registered_capital: '注册资本',
  registered_address: '注册地址',
  business_term: '营业期限',
  approval_date: '核准日期',
  region: '所属地区',
  credit_code: '统一社会信用代码',
  former_name: '曾用名',
  registration_authority: '登记机关',
  industry_category: '所属行业',
  business_scope: '经营范围',
} as const;

// 职位信息表字段中英文映射
export const POSITION_FIELD_NAME_MAP = {
  position_name: '职位名称',
  position_type: '职位类型',
  position_location: '职位地点',
  position_status: '职位状态',
  salary_range: '薪资范围',
  experience_requirement: '工作经验',
  education_requirement: '学历要求',
  company_benefits: '公司福利',
  position_tags: '职位标签',
  position_description: '职位描述',
  position_address: '职位地址',
  publisher_name: 'boss职位发布人',
  publisher_avatar: 'boss职位发布人头像',
  company_link: '公司链接',
  company_name: '公司名称',
  position_image: '职位详情图像',
} as const; 